// Code generated by github.com/xfrr/assemble; DO NOT EDIT.
package main

import (
	"context"
	"time"

	assemble "github.com/xfrr/assemble"
)

//go:generate assemble -var Core -o ./example/core_assemble_gen.go
func Assemble() (*assemble.Container, error) {
	regs := make([]assemble.Registrar, 0, 6)
	regs = append(regs, assemble.Provide[Logger](func(_ assemble.Resolver) (Logger, error) {
		z, err := NewZapLogger()
		if err != nil {
			return nil, err
		}
		return Logger(z), nil
	}))
	regs = append(regs, assemble.Provide[*Server](func(r assemble.Resolver) (*Server, error) { return NewServer(r) }))
	regs = append(regs, assemble.Set(
		assemble.Append(func(r assemble.Resolver) (Middleware, error) { return NewAuthMW(r) }),
		assemble.Append(func(r assemble.Resolver) (Middleware, error) { return NewRecoverMW(r) }),
	))
	regs = append(regs, assemble.OnStart(func(ctx context.Context, r assemble.Resolver) error { return StartHTTP(r) }))
	regs = append(regs, assemble.OnStop(func(ctx context.Context, r assemble.Resolver) error {
		srv, err := assemble.Get[*Server](r)
		if err == nil {
			srv.log.Infof("HTTP server stopping...")
		}
		return nil
	}))
	regs = append(regs, assemble.OnStopFor(func(ctx context.Context, r assemble.Resolver, srv *Server) error {
		srv.log.Infof("Server: graceful shutdown...")
		return nil
	}, assemble.WithStopTimeout(time.Duration(5000)*time.Millisecond)))
	c, err := assemble.Assemble(assemble.Module(regs))
	if err != nil {
		return nil, err
	}
	return c, nil
}
