// Code generated by github.com/xfrr/assemble; DO NOT EDIT.
package main

import (
	"context"
	"time"

	assemble "github.com/xfrr/assemble"
	di "github.com/xfrr/assemble/example/di"
)

//go:generate assemble -var Core -o core_assemble_gen.go
func Assemble() (*assemble.Container, error) {
	regs := make([]assemble.Registrar, 0, 6)
	regs = append(regs, assemble.Provide[di.SimpleLogger](func(_ context.Context, _ assemble.Resolver) (di.SimpleLogger, error) {
		z, err := di.NewSimpleLogger()
		if err != nil {
			return di.SimpleLogger{}, err
		}
		return z, nil
	}))
	regs = append(regs, assemble.Provide[*di.InMemoryRepo](func(_ context.Context, _ assemble.Resolver) (*di.InMemoryRepo, error) {
		return di.NewInMemoryRepo()
	}))
	regs = append(regs, assemble.Provide[*Server](func(ctx context.Context, r assemble.Resolver) (*Server, error) { return NewServer(ctx, r) }))
	regs = append(regs, assemble.OnStart(func(ctx context.Context, r assemble.Resolver) error { return StartServer(ctx, r) }))
	regs = append(regs, assemble.OnStop(func(ctx context.Context, r assemble.Resolver) error {
		srv, err := assemble.Get[*Server](ctx, r)
		if err == nil {
			srv.logger.Infof("HTTP server stopping...")
		}
		return nil
	}))
	regs = append(regs, assemble.OnStopFor(func(_ context.Context, _ assemble.Resolver, srv *Server) error {
		srv.logger.Infof("Server: graceful shutdown...")
		return nil
	}, assemble.WithStopTimeout(time.Duration(5000)*time.Millisecond)))
	c, err := assemble.Assemble(assemble.Module(regs))
	if err != nil {
		return nil, err
	}
	return c, nil
}
