//go:build !assemble_codegen
// +build !assemble_codegen

// Code generated by github.com/xfrr/assemble; DO NOT EDIT.
package di

import (
	"context"
	"time"

	assemble "github.com/xfrr/assemble"
)

//go:generate assemble -var Core -o assemble_server_gen.go
func AssembleCore() (*assemble.Container, error) {
	regs := make([]assemble.Registrar, 0, 6)
	regs = append(regs, assemble.Provide[SimpleLogger](func(_ context.Context, _ assemble.Resolver) (SimpleLogger, error) {
		z, err := NewSimpleLogger()
		if err != nil {
			return SimpleLogger{}, err
		}
		return z, nil
	}))
	regs = append(regs, assemble.Provide[*InMemoryRepo](func(_ context.Context, _ assemble.Resolver) (*InMemoryRepo, error) {
		return NewInMemoryRepo()
	}))
	regs = append(regs, assemble.Provide[*Server](func(ctx context.Context, r assemble.Resolver) (*Server, error) { return NewServer(ctx, r) }))
	regs = append(regs, assemble.OnStart(func(ctx context.Context, r assemble.Resolver) error { return StartServer(ctx, r) }))
	regs = append(regs, assemble.OnStop(func(ctx context.Context, r assemble.Resolver) error {
		logger, err := assemble.Get[SimpleLogger](ctx, r)
		if err != nil {
			return err
		}
		logger.Infof("Core module: shutdown complete.")
		return nil
	}))
	regs = append(regs, assemble.OnStopFor(func(_ context.Context, _ assemble.Resolver, srv *Server) error {
		srv.Logger.Infof("Server: graceful shutdown...")
		return nil
	}, assemble.WithStopTimeout(time.Duration(5000)*time.Millisecond)))
	c, err := assemble.Assemble(assemble.Module(regs))
	if err != nil {
		return nil, err
	}
	return c, nil
}
