package render

import (
	"bytes"
	"fmt"
	"go/format"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"github.com/xfrr/assemble/internal/parser"
)

/* =========================
   Constants
   ========================= */

const (
	importPathAssemble = "github.com/xfrr/assemble"
	importStdContext   = "context"
	importStdTime      = "time"

	aliasAssemble = "assemble"

	genDirectiveFmt    = "//go:generate assemble "
	genVarDirectiveFmt = genDirectiveFmt + "-var %s -o %s\n"
	genFnDirectiveFmt  = genDirectiveFmt + "-fn %s -o %s\n"

	fileHeaderFmt = "// Code generated by %s; DO NOT EDIT.\npackage %s\n\n"
	fileHeaderTag = "//go:build !assemble_codegen\n\n" + "// +build !assemble_codegen\n\n"

	makeRegsFmt = "  regs := make([]assemble.Registrar, 0, %d)\n"

	appendSetOpen  = "  regs = append(regs, assemble.Set"
	appendSetClose = "  ))\n"

	assembleStartCallFmtExact = "func %s() (*assemble.Container, error) {\n"
	assembleEndBody           = "" +
		"  c, err := assemble.Assemble(assemble.Module(regs))\n" +
		"  if err != nil { return nil, err }\n" +
		"  return c, nil\n" +
		"}\n"
)

/* =========================
   Public API
   ========================= */

type Config struct {
	IsVarBased     bool
	VarName        string
	FuncName       string
	OutFilePath    string
	PkgName        string
	CurrentPkgPath string
}

// EmitWithFunc produces a Go file using an exact function name (e.g., "AssembleServer").
func EmitWithFunc(m parser.Model, cfg Config) (string, error) {
	var b bytes.Buffer

	writeHeader(&b, cfg.PkgName)

	noAlias, aliased := normalizeImports(m.Imports, needsTime(m))

	// path -> ident (for call sites)
	aliasMap := buildAliasMap(noAlias, aliased)
	// pkg-name -> ident (for type strings)
	nameMap := buildNameToIdent(noAlias, aliased)

	writeImports(&b, noAlias, aliased)
	writeAssembleStartExact(&b, m, cfg)

	writeProvides(&b, m.Provides, aliasMap, nameMap, cfg.CurrentPkgPath)
	writeSets(&b, m.Sets, aliasMap, nameMap, cfg.CurrentPkgPath)
	writeBinds(&b, m.Binds, nameMap)
	writeStarts(&b, m.Starts, aliasMap, nameMap, cfg.CurrentPkgPath)
	writeStops(&b, m.Stops, aliasMap, nameMap, cfg.CurrentPkgPath)

	writeAssembleEnd(&b)

	return formatOrRaw(b.Bytes())
}

/* =========================
   Top-level file sections
   ========================= */

func writeHeader(b *bytes.Buffer, pkgName string) {
	fmt.Fprint(b, fileHeaderTag)
	fmt.Fprintf(b, fileHeaderFmt, importPathAssemble, pkgName)
}

func writeImports(b *bytes.Buffer, noAlias, aliased []parser.Import) {
	b.WriteString("import (\n")
	for _, imp := range noAlias {
		fmt.Fprintf(b, "  %q\n", imp.Path)
	}
	if len(noAlias) > 0 && len(aliased) > 0 {
		b.WriteString("\n")
	}
	for _, imp := range aliased {
		fmt.Fprintf(b, "  %s %q\n", imp.Alias, imp.Path)
	}
	b.WriteString(")\n\n")
}

func writeAssembleStartExact(b *bytes.Buffer, m parser.Model, cfg Config) {
	outFile := filepath.Base(cfg.OutFilePath)
	if cfg.IsVarBased {
		fmt.Fprintf(b, genVarDirectiveFmt, cfg.VarName, outFile)
	} else {
		fmt.Fprintf(b, genFnDirectiveFmt, cfg.FuncName, outFile)
	}
	fmt.Fprintf(b, assembleStartCallFmtExact, cfg.FuncName)

	total := len(m.Provides) + len(m.Sets) + len(m.Binds) + len(m.Starts) + len(m.Stops)
	fmt.Fprintf(b, makeRegsFmt, total)
}

func writeAssembleEnd(b *bytes.Buffer) {
	b.WriteString(assembleEndBody)
}

/* =========================
   Writers for each model section
   ========================= */

func writeProvides(
	b *bytes.Buffer,
	provides []parser.Provide,
	aliasMap map[string]string,
	nameMap map[string]string,
	curPkg string,
) {
	for _, p := range provides {
		opt := renderNameOpt(p.Named)

		// Function-literal providers need special handling.
		if p.IsFuncLit {
			if p.ResType != "" {
				p.ResType = requalifyTypeString(p.ResType, nameMap)
			}
			writeProvideFuncLit(b, p, opt, nameMap)
			continue
		}

		ctor := qualified(p, aliasMap, curPkg)
		resType := requalifyTypeString(p.ResType, nameMap)

		wrap := buildProviderWrapper(p, ctor, resType)
		// assemble.Provide[T](wrap)
		fmt.Fprintf(b, "  regs = append(regs, assemble.Provide%s(%s%s))\n", generic(resType), wrap, opt)
	}
}

func writeProvideFuncLit(b *bytes.Buffer, p parser.Provide, opt string, nameMap map[string]string) {
	resType := requalifyTypeString(p.ResType, nameMap)

	// If the literal already has the correct shape (ctx, resolver) and returns (T, error), we can pass it as-is.
	if p.TakesResolve && p.LitResultCount == 2 && p.HasError {
		fmt.Fprintf(b, "  regs = append(regs, assemble.Provide%s(%s%s))\n",
			generic(resType), removeBlankLines(p.RawFuncLit), opt)
		return
	}

	call := "prov()"
	if p.LitParamCount == 2 || p.TakesResolve {
		call = "prov(ctx, r)"
	}
	rawFn := removeBlankLines(p.RawFuncLit)

	if p.LitResultCount == 2 || p.HasError {
		fmt.Fprintf(
			b,
			"  regs = append(regs, assemble.Provide%s(func(ctx context.Context, r assemble.Resolver)(%s, error){ prov := %s; return %s }%s))\n",
			generic(resType),
			resType,
			rawFn,
			call,
			opt,
		)
		return
	}

	// Single-result provider; wrap into (T, error)
	fmt.Fprintf(
		b,
		"  regs = append(regs, assemble.Provide%s(func(ctx context.Context, r assemble.Resolver)(%s, error){ prov := %s; v := %s; return v, nil }%s))\n",
		generic(resType),
		resType,
		rawFn,
		call,
		opt,
	)
}

func writeSets(
	b *bytes.Buffer,
	sets []parser.Set,
	aliasMap map[string]string,
	nameMap map[string]string,
	curPkg string,
) {
	for _, s := range sets {
		elemType := requalifyTypeString(s.ElemType, nameMap)

		b.WriteString(appendSetOpen)
		if tp := generic(elemType); tp != "" {
			b.WriteString(tp)
		}
		b.WriteString("(\n")

		for _, el := range s.Elems {
			ctor := qualified(el, aliasMap, curPkg)
			elWrap := buildProviderWrapper(el, ctor, requalifyTypeString(el.ResType, nameMap))
			// assemble.Append[T](wrap) or assemble.Append(wrap) if T is empty
			fmt.Fprintf(b, "    assemble.Append%s(%s),\n", generic(elemType), elWrap)
		}

		b.WriteString(appendSetClose)
	}
}

func writeBinds(b *bytes.Buffer, binds []parser.Bind, nameMap map[string]string) {
	for _, bd := range binds {
		iface := requalifyTypeString(bd.IfaceType, nameMap)
		impl := requalifyTypeString(bd.ImplType, nameMap)
		opt := renderNameOpt(bd.Named)

		// assemble.Bind[IFace](assemble.As[Impl](), opts...)
		fmt.Fprintf(
			b,
			"  regs = append(regs, assemble.Bind%s(assemble.As%s()%s))\n",
			generic(iface), generic(impl), opt,
		)
	}
}

func writeStarts(
	b *bytes.Buffer,
	starts []parser.StartHook,
	aliasMap map[string]string,
	nameMap map[string]string,
	curPkg string,
) {
	for _, h := range starts {
		opts := startOpts(h)

		if h.IsStartFor {
			call := hookCallForStartFor(h, aliasMap, nameMap, curPkg)
			if h.ForType != "" {
				ft := requalifyTypeString(h.ForType, nameMap)
				fmt.Fprintf(b, "  regs = append(regs, assemble.OnStartFor%s(%s%s))\n", generic(ft), call, opts)
			} else {
				fmt.Fprintf(b, "  regs = append(regs, assemble.OnStartFor(%s%s))\n", call, opts)
			}
			continue
		}

		call := startHookCall(h, aliasMap, curPkg)
		fmt.Fprintf(b, "  regs = append(regs, assemble.OnStart(%s%s))\n", call, opts)
	}
}

func writeStops(
	b *bytes.Buffer,
	stops []parser.StopHook,
	aliasMap map[string]string,
	nameMap map[string]string,
	curPkg string,
) {
	for _, h := range stops {
		opts := stopOpts(h)

		if h.IsStopFor {
			call := hookCallForStopFor(h, aliasMap, nameMap, curPkg)
			if h.ForType != "" {
				ft := requalifyTypeString(h.ForType, nameMap)
				fmt.Fprintf(b, "  regs = append(regs, assemble.OnStopFor%s(%s%s))\n", generic(ft), call, opts)
			} else {
				fmt.Fprintf(b, "  regs = append(regs, assemble.OnStopFor(%s%s))\n", call, opts)
			}
			continue
		}

		call := stopHookCall(h, aliasMap, curPkg)
		fmt.Fprintf(b, "  regs = append(regs, assemble.OnStop(%s%s))\n", call, opts)
	}
}

/* =========================
   Imports Handling
   ========================= */

func normalizeImports(parsed []parser.Import, includeTime bool) ([]parser.Import, []parser.Import) {
	seen := map[string]parser.Import{}

	// Required imports
	seen[importStdContext] = parser.Import{Alias: "", Path: importStdContext}
	seen[importPathAssemble] = parser.Import{Alias: aliasAssemble, Path: importPathAssemble}
	if includeTime {
		seen[importStdTime] = parser.Import{Alias: "", Path: importStdTime}
	}

	for _, imp := range parsed {
		if imp.Path == "" {
			continue
		}
		// Force the "assemble" alias for our own package
		if imp.Path == importPathAssemble {
			seen[imp.Path] = parser.Import{Alias: aliasAssemble, Path: imp.Path}
			continue
		}
		if _, ok := seen[imp.Path]; !ok {
			seen[imp.Path] = imp
		}
	}

	noAlias := make([]parser.Import, 0, len(seen))
	aliased := make([]parser.Import, 0, len(seen))
	for _, im := range seen {
		if im.Alias == "" {
			noAlias = append(noAlias, im)
		} else {
			aliased = append(aliased, im)
		}
	}

	sort.Slice(noAlias, func(i, j int) bool { return noAlias[i].Path < noAlias[j].Path })
	sort.Slice(aliased, func(i, j int) bool {
		if aliased[i].Alias != aliased[j].Alias {
			return aliased[i].Alias < aliased[j].Alias
		}
		return aliased[i].Path < aliased[j].Path
	})

	return noAlias, aliased
}

/* =========================
   Formatting / utils
   ========================= */

// buildAliasMap returns the identifier used in code for each import path.
// For non-aliased imports, derive the default name from the last path segment.
func buildAliasMap(noAlias, aliased []parser.Import) map[string]string {
	m := make(map[string]string, len(noAlias)+len(aliased))
	for _, im := range noAlias {
		m[im.Path] = lastSegment(im.Path)
	}
	for _, im := range aliased {
		m[im.Path] = im.Alias
	}
	return m
}

func lastSegment(pth string) string {
	return path.Base(pth)
}

func needsTime(m parser.Model) bool {
	uses := func(timeoutExpr string, timeoutMs int64) bool {
		if timeoutExpr != "" {
			return strings.Contains(timeoutExpr, "time.")
		}
		return timeoutMs > 0
	}
	for _, h := range m.Starts {
		if uses(h.TimeoutExpr, h.TimeoutMs) {
			return true
		}
	}
	for _, h := range m.Stops {
		if uses(h.TimeoutExpr, h.TimeoutMs) {
			return true
		}
	}
	return false
}

func formatOrRaw(src []byte) (string, error) {
	formatted, err := format.Source(src)
	if err != nil {
		//nolint:nilerr // Return unformatted source on error.
		return string(src), nil
	}
	return string(formatted), nil
}

func renderNameOpt(name string) string {
	if name == "" {
		return ""
	}
	return fmt.Sprintf(", assemble.Name(%q)", name)
}

// qualified returns the proper reference to a provider constructor,
// honoring the alias in the import block. If ctor is in the same package, return just the function name.
func qualified(p parser.Provide, aliasMap map[string]string, curPkg string) string {
	if p.PkgPath == "" || p.PkgPath == curPkg {
		return p.FuncName
	}
	if alias, ok := aliasMap[p.PkgPath]; ok && alias != "" {
		return alias + "." + p.FuncName
	}
	if p.PkgAlias != "" {
		return p.PkgAlias + "." + p.FuncName
	}
	return lastSegment(p.PkgPath) + "." + p.FuncName
}

// buildProviderWrapper wraps any constructor shape into the canonical factory func(ctx, r)(T, error).
func buildProviderWrapper(p parser.Provide, ctor string, resType string) string {
	switch {
	case p.TakesResolve && p.HasError:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s(ctx, r) }",
			resType, ctor,
		)
	case p.TakesResolve && !p.HasError:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s(ctx, r), nil }",
			resType, ctor)
	case !p.TakesResolve && p.HasError:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s() }",
			resType, ctor)
	default:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s(), nil }",
			resType, ctor)
	}
}

// buildNameToIdent maps package *name* (usually last path segment) to the identifier used in code.
// If an alias is present, we map the package name to that alias.
func buildNameToIdent(noAlias, aliased []parser.Import) map[string]string {
	m := make(map[string]string, len(noAlias)+len(aliased))

	// Non-aliased imports: map pkg-name -> pkg-name
	for _, im := range noAlias {
		name := lastSegment(im.Path)
		m[name] = name
	}

	// Aliased imports: map pkg-name -> alias
	for _, im := range aliased {
		name := lastSegment(im.Path)
		ident := im.Alias
		if ident == "" {
			ident = name
		}
		m[name] = ident
	}

	// Defensive: also map the alias itself to itself so that requalification
	// is a no-op if types were already emitted with that identifier.
	for _, im := range aliased {
		if im.Alias != "" {
			m[im.Alias] = im.Alias
		}
	}

	return m
}

// Re-qualify a type string produced by types.TypeString (which uses package *names*)
// so that it uses the *identifiers* present in the import block (aliases or default names).
func requalifyTypeString(typ string, nameToIdent map[string]string) string {
	if typ == "" || len(nameToIdent) == 0 {
		return typ
	}

	// Replace longer keys first to avoid partial overlaps.
	keys := make([]string, 0, len(nameToIdent))
	for k := range nameToIdent {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return len(keys[i]) > len(keys[j]) })

	out := typ
	for _, name := range keys {
		ident := nameToIdent[name]
		if ident == "" || ident == name {
			continue
		}
		out = strings.ReplaceAll(out, name+".", ident+".")
	}
	return out
}

/* =========================
   Hooks Handling
   ========================= */

func startHookCall(h parser.StartHook, aliasMap map[string]string, curPkg string) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}
	fn := hookQualifiedName(h.PkgPath, h.FuncName, h.PkgAlias, aliasMap, curPkg)
	return "func(ctx context.Context, r assemble.Resolver) error { return " + fn + "(ctx, r) }"
}

func stopHookCall(h parser.StopHook, aliasMap map[string]string, curPkg string) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}
	fn := hookQualifiedName(h.PkgPath, h.FuncName, h.PkgAlias, aliasMap, curPkg)
	return "func(ctx context.Context, r assemble.Resolver) error { return " + fn + "(ctx, r) }"
}

func hookCallForStartFor(
	h parser.StartHook,
	aliasMap map[string]string,
	nameMap map[string]string,
	curPkg string,
) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}

	fn := hookQualifiedName(h.PkgPath, h.FuncName, h.PkgAlias, aliasMap, curPkg)
	ft := requalifyTypeString(h.ForType, nameMap)

	switch {
	case h.FnHasCtx && h.FnHasResolve:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(ctx, r, t) }",
			ft, fn)
	case !h.FnHasCtx && h.FnHasResolve:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(r, t) }",
			ft, fn)
	default:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(t) }",
			ft, fn)
	}
}

func hookCallForStopFor(
	h parser.StopHook,
	aliasMap map[string]string,
	nameMap map[string]string,
	curPkg string,
) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}

	fn := hookQualifiedName(h.PkgPath, h.FuncName, h.PkgAlias, aliasMap, curPkg)
	ft := requalifyTypeString(h.ForType, nameMap)

	switch {
	case h.FnHasCtx && h.FnHasResolve:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(ctx, r, t) }",
			ft, fn)
	case !h.FnHasCtx && h.FnHasResolve:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(r, t) }",
			ft, fn)
	default:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(t) }",
			ft, fn)
	}
}

func hookQualifiedName(pkgPath, fnName, parsedAlias string, aliasMap map[string]string, curPkgPath string) string {
	if pkgPath == "" || pkgPath == curPkgPath {
		return fnName
	}
	if alias, ok := aliasMap[pkgPath]; ok && alias != "" {
		return alias + "." + fnName
	}
	if parsedAlias != "" {
		return parsedAlias + "." + fnName
	}
	return lastSegment(pkgPath) + "." + fnName
}

func startOpts(h parser.StartHook) string {
	var parts []string
	if h.Priority != 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithPriority(%d)", h.Priority))
	}
	if h.TimeoutExpr != "" {
		parts = append(parts, fmt.Sprintf("assemble.WithStartTimeout(%s)", h.TimeoutExpr))
	} else if h.TimeoutMs > 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithStartTimeout(time.Duration(%d)*time.Millisecond)", h.TimeoutMs))
	}
	if len(parts) == 0 {
		return ""
	}
	return ", " + strings.Join(parts, ", ")
}

func stopOpts(h parser.StopHook) string {
	var parts []string
	if h.Priority != 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithPriority(%d)", h.Priority))
	}
	if h.TimeoutExpr != "" {
		parts = append(parts, fmt.Sprintf("assemble.WithStopTimeout(%s)", h.TimeoutExpr))
	} else if h.TimeoutMs > 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithStopTimeout(time.Duration(%d)*time.Millisecond)", h.TimeoutMs))
	}
	if len(parts) == 0 {
		return ""
	}
	return ", " + strings.Join(parts, ", ")
}

func removeBlankLines(s string) string {
	lines := strings.Split(s, "\n")
	out := make([]string, 0, len(lines))
	for _, ln := range lines {
		if strings.TrimSpace(ln) != "" {
			out = append(out, ln)
		}
	}
	return strings.Join(out, "\n")
}

// generic renders a generic type parameter list (e.g., "[T]") only if non-empty.
func generic(typeStr string) string {
	if strings.TrimSpace(typeStr) == "" {
		return ""
	}
	return "[" + typeStr + "]"
}
