package render

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/xfrr/assemble/internal/parser"
)

const assembleImport = "github.com/xfrr/assemble"

// Emit generates the container build file from a parsed model.
// It delegates work to smaller helpers to keep responsibilities focused.
func Emit(varName, pkgName, outfile string, m parser.Model) (string, error) {
	var b bytes.Buffer

	writeHeader(&b, pkgName)
	writeImports(&b, m.Imports, needsTime(m))
	writeAssembleStart(&b, m, varName, outfile)

	writeProvides(&b, m.Provides)
	writeSets(&b, m.Sets)
	writeBinds(&b, m.Binds)
	writeStarts(&b, m.Starts)
	writeStops(&b, m.Stops)

	writeAssembleEnd(&b)

	return formatOrRaw(b.Bytes())
}

// --- top-level sections ---

func writeHeader(b *bytes.Buffer, pkgName string) {
	fmt.Fprintf(b, "// Code generated by %s; DO NOT EDIT.\npackage %s\n\n", assembleImport, pkgName)
}

func writeImports(b *bytes.Buffer, imports []parser.Import, includeTime bool) {
	b.WriteString("import (\n")
	if includeTime && !isPackageImported("time", imports) {
		b.WriteString("  \"time\"\n")
	}
	sorted := importsSorted(imports)
	for _, imp := range sorted {
		fmt.Fprintf(b, "  %s %q\n", imp.Alias, imp.Path)
	}
	b.WriteString(")\n\n")
}

func writeAssembleStart(b *bytes.Buffer, m parser.Model, varName, outFile string) {
	fmt.Fprintf(b, "//go:generate assemble -var %s -o %s\n", varName, outFile)
	b.WriteString("func Assemble() (*assemble.Container, error) {\n")
	total := len(m.Provides) + len(m.Sets) + len(m.Binds) + len(m.Starts) + len(m.Stops)
	fmt.Fprintf(b, "  regs := make([]assemble.Registrar, 0, %d)\n", total)
}

func writeAssembleEnd(b *bytes.Buffer) {
	b.WriteString("  c, err := assemble.Assemble(assemble.Module(regs))\n")
	b.WriteString("  if err != nil { return nil, err }\n")
	b.WriteString("  return c, nil\n")
	b.WriteString("}\n")
}

func writeProvides(b *bytes.Buffer, provides []parser.Provide) {
	for _, p := range provides {
		opt := ""
		if p.Named != "" {
			opt = fmt.Sprintf(", assemble.Name(%q)", p.Named)
		}

		if p.IsFuncLit {
			if p.TakesResolve && p.LitResultCount == 2 && p.HasError {
				fmt.Fprint(b, "  regs = append(regs, assemble.Provide")
				if p.ResType != "" {
					fmt.Fprintf(b, "[%s]", p.ResType)
				}
				fmt.Fprintf(b, "(%s%s))\n", removeBlankLines(p.RawFuncLit), opt)
				continue
			}

			call := "prov()"
			if p.LitParamCount == 2 || p.TakesResolve {
				call = "prov(ctx, r)"
			}

			rawFn := removeBlankLines(p.RawFuncLit)
			if p.LitResultCount == 2 || p.HasError {
				fmt.Fprintf(b,
					"  regs = append(regs, assemble.Provide[%s](func(ctx context.Context, r assemble.Resolver)(%s, error){ prov := %s; return %s }%s))\n",
					p.ResType, p.ResType, rawFn, call, opt)
			} else {
				fmt.Fprintf(b,
					"  regs = append(regs, assemble.Provide[%s](func(ctx context.Context, r assemble.Resolver)(%s, error){ prov := %s; v := %s; return v, nil }%s))\n",
					p.ResType, p.ResType, rawFn, call, opt)
			}
			continue
		}

		ctor := qual(p)
		wrap := buildProviderWrapper(p, ctor)
		fmt.Fprintf(b, "  regs = append(regs, assemble.Provide[%s](%s%s))\n", p.ResType, wrap, opt)
	}
}

func writeSets(b *bytes.Buffer, sets []parser.Set) {
	for _, s := range sets {
		b.WriteString("  regs = append(regs, assemble.Set")
		if s.ElemType != "" {
			fmt.Fprintf(b, "[%s]", s.ElemType)
		}
		b.WriteString("(\n")
		for _, el := range s.Elems {
			ctor := qual(el)
			elwrap := buildProviderWrapper(el, ctor)
			b.WriteString("    assemble.Append")
			if s.ElemType != "" {
				fmt.Fprintf(b, "[%s]", s.ElemType)
			}
			fmt.Fprintf(b, "(%s),\n", elwrap)
		}
		b.WriteString("  ))\n")
	}
}

func writeBinds(b *bytes.Buffer, binds []parser.Bind) {
	for _, bd := range binds {
		opt := ""
		if bd.Named != "" {
			opt = fmt.Sprintf(", assemble.Name(%q)", bd.Named)
		}
		fmt.Fprintf(b, "  regs = append(regs, assemble.Bind[%s](assemble.As[%s]()%s))\n", bd.IfaceType, bd.ImplType, opt)
	}
}

func writeStarts(b *bytes.Buffer, starts []parser.StartHook) {
	for _, h := range starts {
		opts := startOpts(h)
		if h.IsStartFor {
			call := hookCallForStartFor(h)
			if h.ForType != "" {
				fmt.Fprintf(b, "  regs = append(regs, assemble.OnStartFor[%s](%s%s))\n", h.ForType, call, opts)
			} else {
				fmt.Fprintf(b, "  regs = append(regs, assemble.OnStartFor(%s%s))\n", call, opts)
			}
		} else {
			call := startHookCall(h)
			fmt.Fprintf(b, "  regs = append(regs, assemble.OnStart(%s%s))\n", call, opts)
		}
	}
}

func writeStops(b *bytes.Buffer, stops []parser.StopHook) {
	for _, h := range stops {
		opts := stopOpts(h)
		if h.IsStopFor {
			call := hookCallForStopFor(h)
			if h.ForType != "" {
				fmt.Fprintf(b, "  regs = append(regs, assemble.OnStopFor[%s](%s%s))\n", h.ForType, call, opts)
			} else {
				fmt.Fprintf(b, "  regs = append(regs, assemble.OnStopFor(%s%s))\n", call, opts)
			}
		} else {
			call := stopHookCall(h)
			fmt.Fprintf(b, "  regs = append(regs, assemble.OnStop(%s%s))\n", call, opts)
		}
	}
}

// --- helpers ---

func needsTime(m parser.Model) bool {
	check := func(timeoutExpr string, timeoutMs int64) bool {
		if timeoutExpr != "" && strings.Contains(timeoutExpr, "time.") {
			return true
		}
		return timeoutExpr == "" && timeoutMs > 0
	}
	for _, h := range m.Starts {
		if check(h.TimeoutExpr, h.TimeoutMs) {
			return true
		}
	}
	for _, h := range m.Stops {
		if check(h.TimeoutExpr, h.TimeoutMs) {
			return true
		}
	}
	return false
}

func formatOrRaw(src []byte) (string, error) {
	formatted, err := format.Source(src)
	if err != nil {
		// preserve prior behavior: return unformatted but compilable code
		return string(src), nil
	}
	return string(formatted), nil
}

func importsSorted(imports []parser.Import) []parser.Import {
	sort.Slice(imports, func(i, j int) bool {
		return imports[i].Alias < imports[j].Alias
	})
	return imports
}

func isPackageImported(pkg string, imports []parser.Import) bool {
	for _, imp := range imports {
		if imp.Path == pkg {
			return true
		}
	}
	return false
}

func qual(p parser.Provide) string {
	if p.PkgAlias != "" {
		return p.PkgAlias + "." + p.FuncName
	}
	return p.FuncName
}

func buildProviderWrapper(p parser.Provide, ctor string) string {
	switch {
	case p.TakesResolve && p.HasError:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s(ctx, r) }", p.ResType, ctor)
	case p.TakesResolve && !p.HasError:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s(ctx, r), nil }", p.ResType, ctor)
	case !p.TakesResolve && p.HasError:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s(ctx, r) }", p.ResType, ctor)
	default:
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s(ctx, r), nil }", p.ResType, ctor)
	}
}

// startHookCall adapts a start hook to func(ctx context.Context, r assemble.Resolver) error.
func startHookCall(h parser.StartHook) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}
	fn := h.FuncName
	if h.PkgAlias != "" {
		fn = h.PkgAlias + "." + fn
	}
	return "func(ctx context.Context, r assemble.Resolver) error { return " + fn + "(ctx, r) }"
}

// stopHookCall adapts a stop hook to func(ctx context.Context, r assemble.Resolver) error.
func stopHookCall(h parser.StopHook) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}
	fn := h.FuncName
	if h.PkgAlias != "" {
		fn = h.PkgAlias + "." + fn
	}
	return "func(ctx context.Context, r assemble.Resolver) error { return " + fn + "(ctx, r) }"
}

func startOpts(h parser.StartHook) string {
	var parts []string
	if h.Priority != 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithPriority(%d)", h.Priority))
	}
	if h.TimeoutExpr != "" {
		parts = append(parts, fmt.Sprintf("assemble.WithStartTimeout(%s)", h.TimeoutExpr))
	} else if h.TimeoutMs > 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithStartTimeout(time.Duration(%d)*time.Millisecond)", h.TimeoutMs))
	}
	if len(parts) == 0 {
		return ""
	}
	return ", " + strings.Join(parts, ", ")
}

func stopOpts(h parser.StopHook) string {
	var parts []string
	if h.Priority != 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithPriority(%d)", h.Priority))
	}
	if h.TimeoutExpr != "" {
		parts = append(parts, fmt.Sprintf("assemble.WithStopTimeout(%s)", h.TimeoutExpr))
	} else if h.TimeoutMs > 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithStopTimeout(time.Duration(%d)*time.Millisecond)", h.TimeoutMs))
	}
	if len(parts) == 0 {
		return ""
	}
	return ", " + strings.Join(parts, ", ")
}

func hookCallForStartFor(h parser.StartHook) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}
	fn := h.FuncName
	if h.PkgAlias != "" {
		fn = h.PkgAlias + "." + fn
	}
	if h.FnHasCtx && h.FnHasResolve {
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(ctx, r, t) }", h.ForType, fn)
	}
	if !h.FnHasCtx && h.FnHasResolve {
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(r, t) }", h.ForType, fn)
	}
	return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(t) }", h.ForType, fn)
}

func hookCallForStopFor(h parser.StopHook) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}

	fn := h.FuncName
	if h.PkgAlias != "" {
		fn = h.PkgAlias + "." + fn
	}
	if h.FnHasCtx && h.FnHasResolve {
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(ctx, r, t) }", h.ForType, fn)
	}
	if !h.FnHasCtx && h.FnHasResolve {
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(r, t) }", h.ForType, fn)
	}
	return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(t) }", h.ForType, fn)
}

func removeBlankLines(s string) string {
	lines := strings.Split(s, "\n")
	var nonBlank []string
	for _, line := range lines {
		if strings.TrimSpace(line) != "" {
			nonBlank = append(nonBlank, line)
		}
	}
	return strings.Join(nonBlank, "\n")
}
