package render

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/xfrr/assemble/internal/parser"
)

/* =========================
   Constants / well-known ids
   ========================= */

const (
	importPathAssemble = "github.com/xfrr/assemble"
	importStdContext   = "context"
	importStdTime      = "time"

	aliasAssemble = "assemble"

	genDirectiveFmt  = "//go:generate assemble -var %s -o %s\n"
	fileHeaderFmt    = "// Code generated by %s; DO NOT EDIT.\npackage %s\n\n"
	makeRegsFmt      = "  regs := make([]assemble.Registrar, 0, %d)\n"
	appendProvideFmt = "  regs = append(regs, assemble.Provide[%s](%s%s))\n"
	appendSetOpen    = "  regs = append(regs, assemble.Set"
	appendSetClose   = "  ))\n"
	appendBindFmt    = "  regs = append(regs, assemble.Bind[%s](assemble.As[%s]()%s))\n"
	appendStartFmt   = "  regs = append(regs, assemble.OnStart(%s%s))\n"
	appendStopFmt    = "  regs = append(regs, assemble.OnStop(%s%s))\n"
	appendStartFor   = "  regs = append(regs, assemble.OnStartFor[%s](%s%s))\n"
	appendStopFor    = "  regs = append(regs, assemble.OnStopFor[%s](%s%s))\n"

	assembleStartCall = "func Assemble() (*assemble.Container, error) {\n"
	assembleEndBody   = "" +
		"  c, err := assemble.Assemble(assemble.Module(regs))\n" +
		"  if err != nil { return nil, err }\n" +
		"  return c, nil\n" +
		"}\n"
)

/* =========================
   Public API
   ========================= */

// Emit produces a fully-formed Go source file from the parsed model.
func Emit(varName, pkgName, outfile string, m parser.Model) (string, error) {
	var b bytes.Buffer

	writeHeader(&b, pkgName)
	writeImports(&b, m.Imports, needsTime(m))
	writeAssembleStart(&b, m, varName, outfile)

	writeProvides(&b, m.Provides)
	writeSets(&b, m.Sets)
	writeBinds(&b, m.Binds)
	writeStarts(&b, m.Starts)
	writeStops(&b, m.Stops)

	writeAssembleEnd(&b)

	return formatOrRaw(b.Bytes())
}

/* =========================
   Top-level file sections
   ========================= */

func writeHeader(b *bytes.Buffer, pkgName string) {
	fmt.Fprintf(b, fileHeaderFmt, importPathAssemble, pkgName)
}

func writeImports(b *bytes.Buffer, parsed []parser.Import, includeTime bool) {
	noAlias, aliased := normalizeImports(parsed, includeTime) // already sorted
	b.WriteString("import (\n")

	for _, imp := range noAlias {
		fmt.Fprintf(b, "  %q\n", imp.Path)
	}
	b.WriteString("\n")

	for _, imp := range aliased {
		fmt.Fprintf(b, "  %s %q\n", imp.Alias, imp.Path)
	}
	b.WriteString(")\n\n")
}

func writeAssembleStart(b *bytes.Buffer, m parser.Model, varName, outFile string) {
	fmt.Fprintf(b, genDirectiveFmt, varName, outFile)
	b.WriteString(assembleStartCall)
	total := len(m.Provides) + len(m.Sets) + len(m.Binds) + len(m.Starts) + len(m.Stops)
	fmt.Fprintf(b, makeRegsFmt, total)
}

func writeAssembleEnd(b *bytes.Buffer) {
	b.WriteString(assembleEndBody)
}

/* =========================
   Registrars
   ========================= */

func writeProvides(b *bytes.Buffer, provides []parser.Provide) {
	for _, p := range provides {
		opt := renderNameOpt(p.Named)

		if p.IsFuncLit {
			writeProvideFuncLit(b, p, opt)
			continue
		}

		ctor := qualified(p)
		wrap := buildProviderWrapper(p, ctor)
		fmt.Fprintf(b, appendProvideFmt, p.ResType, wrap, opt)
	}
}

func writeProvideFuncLit(b *bytes.Buffer, p parser.Provide, opt string) {
	// If the literal already conforms to (ctx, r) -> (T, error), use directly.
	if p.TakesResolve && p.LitResultCount == 2 && p.HasError {
		fmt.Fprint(b, "  regs = append(regs, assemble.Provide")
		if p.ResType != "" {
			fmt.Fprintf(b, "[%s]", p.ResType)
		}
		fmt.Fprintf(b, "(%s%s))\n", removeBlankLines(p.RawFuncLit), opt)
		return
	}

	// Otherwise, wrap the literal in an adapter with (ctx, r) signature.
	call := "prov()"
	if p.LitParamCount == 2 || p.TakesResolve {
		call = "prov(ctx, r)"
	}
	rawFn := removeBlankLines(p.RawFuncLit)

	if p.LitResultCount == 2 || p.HasError {
		fmt.Fprintf(
			b,
			"  regs = append(regs, assemble.Provide[%s](func(ctx context.Context, r assemble.Resolver)(%s, error){ prov := %s; return %s }%s))\n",
			p.ResType,
			p.ResType,
			rawFn,
			call,
			opt,
		)
	} else {
		fmt.Fprintf(
			b,
			"  regs = append(regs, assemble.Provide[%s](func(ctx context.Context, r assemble.Resolver)(%s, error){ prov := %s; v := %s; return v, nil }%s))\n",
			p.ResType, p.ResType, rawFn, call, opt,
		)
	}
}

func writeSets(b *bytes.Buffer, sets []parser.Set) {
	for _, s := range sets {
		b.WriteString(appendSetOpen)
		if s.ElemType != "" {
			fmt.Fprintf(b, "[%s]", s.ElemType)
		}
		b.WriteString("(\n")
		for _, el := range s.Elems {
			ctor := qualified(el)
			elwrap := buildProviderWrapper(el, ctor)

			b.WriteString("    assemble.Append")
			if s.ElemType != "" {
				fmt.Fprintf(b, "[%s]", s.ElemType)
			}
			fmt.Fprintf(b, "(%s),\n", elwrap)
		}
		b.WriteString(appendSetClose)
	}
}

func writeBinds(b *bytes.Buffer, binds []parser.Bind) {
	for _, bd := range binds {
		opt := renderNameOpt(bd.Named)
		fmt.Fprintf(b, appendBindFmt, bd.IfaceType, bd.ImplType, opt)
	}
}

func writeStarts(b *bytes.Buffer, starts []parser.StartHook) {
	for _, h := range starts {
		opts := startOpts(h)
		if h.IsStartFor {
			call := hookCallForStartFor(h)
			if h.ForType != "" {
				fmt.Fprintf(b, appendStartFor, h.ForType, call, opts)
			} else {
				// Fallback: no generic arg captured by parser
				fmt.Fprintf(b, "  regs = append(regs, assemble.OnStartFor(%s%s))\n", call, opts)
			}
			continue
		}
		call := startHookCall(h)
		fmt.Fprintf(b, appendStartFmt, call, opts)
	}
}

func writeStops(b *bytes.Buffer, stops []parser.StopHook) {
	for _, h := range stops {
		opts := stopOpts(h)
		if h.IsStopFor {
			call := hookCallForStopFor(h)
			if h.ForType != "" {
				fmt.Fprintf(b, appendStopFor, h.ForType, call, opts)
			} else {
				fmt.Fprintf(b, "  regs = append(regs, assemble.OnStopFor(%s%s))\n", call, opts)
			}
			continue
		}
		call := stopHookCall(h)
		fmt.Fprintf(b, appendStopFmt, call, opts)
	}
}

/* =========================
   Import handling
   ========================= */

// normalizeImports merges parsed imports with required ones, dedups by path,
// and returns two sorted lists: no-alias imports first, then aliased ones.
func normalizeImports(parsed []parser.Import, includeTime bool) ([]parser.Import, []parser.Import) {
	seen := map[string]parser.Import{}

	// Required: context (no alias) and assemble (aliased).
	seen[importStdContext] = parser.Import{Alias: "", Path: importStdContext}
	seen[importPathAssemble] = parser.Import{Alias: aliasAssemble, Path: importPathAssemble}
	if includeTime {
		seen[importStdTime] = parser.Import{Alias: "", Path: importStdTime}
	}

	// Merge user imports, keeping first-seen for a path.
	for _, imp := range parsed {
		if imp.Path == "" {
			continue
		}
		// Normalize assemble alias to our preferred one.
		if imp.Path == importPathAssemble {
			// Always enforce alias "assemble" to keep generated code stable.
			seen[imp.Path] = parser.Import{Alias: aliasAssemble, Path: imp.Path}
			continue
		}
		if _, ok := seen[imp.Path]; !ok {
			seen[imp.Path] = imp
		}
	}

	// Materialize into two groups: no-alias first, aliased second.
	noAlias := make([]parser.Import, 0, len(seen))
	aliased := make([]parser.Import, 0, len(seen))
	for _, im := range seen {
		if im.Alias == "" {
			noAlias = append(noAlias, im)
		} else {
			aliased = append(aliased, im)
		}
	}

	// Sort no-alias by path.
	sort.Slice(noAlias, func(i, j int) bool {
		return noAlias[i].Path < noAlias[j].Path
	})

	// Sort aliased by alias, then path (stable grouping).
	sort.Slice(aliased, func(i, j int) bool {
		if aliased[i].Alias != aliased[j].Alias {
			return aliased[i].Alias < aliased[j].Alias
		}
		return aliased[i].Path < aliased[j].Path
	})

	return noAlias, aliased
}

/* =========================
   Formatting / utils
   ========================= */

func needsTime(m parser.Model) bool {
	uses := func(timeoutExpr string, timeoutMs int64) bool {
		if timeoutExpr != "" {
			return strings.Contains(timeoutExpr, "time.")
		}
		return timeoutMs > 0
	}
	for _, h := range m.Starts {
		if uses(h.TimeoutExpr, h.TimeoutMs) {
			return true
		}
	}
	for _, h := range m.Stops {
		if uses(h.TimeoutExpr, h.TimeoutMs) {
			return true
		}
	}
	return false
}

func formatOrRaw(src []byte) (string, error) {
	formatted, err := format.Source(src)
	if err != nil {
		//nolint:nilerr // Preserve compilable output even on formatting failures.
		return string(src), nil
	}
	return string(formatted), nil
}

func renderNameOpt(name string) string {
	if name == "" {
		return ""
	}
	return fmt.Sprintf(", assemble.Name(%q)", name)
}

func qualified(p parser.Provide) string {
	if p.PkgAlias != "" {
		return p.PkgAlias + "." + p.FuncName
	}
	return p.FuncName
}

/*
   Provider wrapper generation

   We adapt any constructor shape into the assembler’s expected provider signature:

       func(ctx context.Context, r assemble.Resolver) (T, error)

   — Without the full signature of the original ctor, we rely on parser flags:
     - TakesResolve: ctor expects a Resolver (we *don’t* assume it also wants ctx)
     - HasError: ctor returns (..., error)

   To avoid incorrect calls (e.g., passing ctx to a ctor that doesn’t take it),
   we only pass the arguments we know it accepts: (r) or ().
*/

func buildProviderWrapper(p parser.Provide, ctor string) string {
	switch {
	case p.TakesResolve && p.HasError:
		// ctor(r) -> (T, error)
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s(ctx, r) }",
			p.ResType,
			ctor,
		)
	case p.TakesResolve && !p.HasError:
		// ctor(r) -> T
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s(ctx, r), nil }",
			p.ResType,
			ctor,
		)
	case !p.TakesResolve && p.HasError:
		// ctor() -> (T, error)
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s() }",
			p.ResType,
			ctor,
		)
	default:
		// ctor() -> T
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver)(%s, error){ return %s(), nil }",
			p.ResType,
			ctor,
		)
	}
}

/* =========================
   Hooks
   ========================= */

func startHookCall(h parser.StartHook) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}
	fn := h.FuncName
	if h.PkgAlias != "" {
		fn = h.PkgAlias + "." + fn
	}
	return "func(ctx context.Context, r assemble.Resolver) error { return " + fn + "(ctx, r) }"
}

func stopHookCall(h parser.StopHook) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}
	fn := h.FuncName
	if h.PkgAlias != "" {
		fn = h.PkgAlias + "." + fn
	}
	return "func(ctx context.Context, r assemble.Resolver) error { return " + fn + "(ctx, r) }"
}

func startOpts(h parser.StartHook) string {
	var parts []string
	if h.Priority != 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithPriority(%d)", h.Priority))
	}
	if h.TimeoutExpr != "" {
		parts = append(parts, fmt.Sprintf("assemble.WithStartTimeout(%s)", h.TimeoutExpr))
	} else if h.TimeoutMs > 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithStartTimeout(time.Duration(%d)*time.Millisecond)", h.TimeoutMs))
	}
	if len(parts) == 0 {
		return ""
	}
	return ", " + strings.Join(parts, ", ")
}

func stopOpts(h parser.StopHook) string {
	var parts []string
	if h.Priority != 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithPriority(%d)", h.Priority))
	}
	if h.TimeoutExpr != "" {
		parts = append(parts, fmt.Sprintf("assemble.WithStopTimeout(%s)", h.TimeoutExpr))
	} else if h.TimeoutMs > 0 {
		parts = append(parts, fmt.Sprintf("assemble.WithStopTimeout(time.Duration(%d)*time.Millisecond)", h.TimeoutMs))
	}
	if len(parts) == 0 {
		return ""
	}
	return ", " + strings.Join(parts, ", ")
}

func hookCallForStartFor(h parser.StartHook) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}
	fn := h.FuncName
	if h.PkgAlias != "" {
		fn = h.PkgAlias + "." + fn
	}
	// Three possible shapes, inferred from parser flags.
	if h.FnHasCtx && h.FnHasResolve {
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(ctx, r, t) }",
			h.ForType,
			fn,
		)
	}
	if !h.FnHasCtx && h.FnHasResolve {
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(r, t) }",
			h.ForType,
			fn,
		)
	}
	return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(t) }",
		h.ForType,
		fn,
	)
}

func hookCallForStopFor(h parser.StopHook) string {
	if h.IsFuncLit && h.RawFuncLit != "" {
		return removeBlankLines(h.RawFuncLit)
	}
	fn := h.FuncName
	if h.PkgAlias != "" {
		fn = h.PkgAlias + "." + fn
	}
	if h.FnHasCtx && h.FnHasResolve {
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(ctx, r, t) }",
			h.ForType,
			fn,
		)
	}
	if !h.FnHasCtx && h.FnHasResolve {
		return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(r, t) }",
			h.ForType,
			fn,
		)
	}
	return fmt.Sprintf("func(ctx context.Context, r assemble.Resolver, t %s) error { return %s(t) }",
		h.ForType,
		fn,
	)
}

/* =========================
   Small string helpers
   ========================= */

func removeBlankLines(s string) string {
	lines := strings.Split(s, "\n")
	out := make([]string, 0, len(lines))
	for _, ln := range lines {
		if strings.TrimSpace(ln) != "" {
			out = append(out, ln)
		}
	}
	return strings.Join(out, "\n")
}
